CREATE TABLE IF NOT EXISTS users(
	user_id INT GENERATED BY DEFAULT AS IDENTITY,
    user_login varchar(256) NOT NULL UNIQUE,
	user_password varchar(256) NOT NULL,
	user_email varchar(256) NOT NULL,
    user_fname varchar(50) NOT NULL,
    user_lname varchar(50) NOT NULL,
	user_role varchar(50) DEFAULT 'student',
	PRIMARY KEY(user_id),
	CHECK(LENGTH(user_login)>=6),
	CHECK(LENGTH(user_password)>=6)
);

CREATE TABLE IF NOT EXISTS students(   
    student_id INT NOT NULL,
    student_curator varchar(50),
    student_group varchar(50),
    CONSTRAINT PK_S PRIMARY KEY (student_id)	
)

CREATE TABLE IF NOT EXISTS teachers(   
    teacher_id INT NOT NULL,
    teacher_title varchar(50),
    teacher_degree varchar(50),
    CONSTRAINT PK_T PRIMARY KEY (teacher_id)	
)

INSERT INTO USERS VALUES (666,'Admin666',
							  'Admin666',
                              'alexanisandr@gmail.com',
                              'Oleksandr',
                              'Anisimov',
                              'admin')